version: '3.8'

services:
  webapi:
    build:
      context: .
      dockerfile: MinimalTaskControl/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: unless-stopped

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: MinimalTaskControl
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: !Q2w3e4r
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: